# this is a sample toml file
[django]
SECRET_KEY = 'django-insecure-^tsfv-1%$xo13m=_*zjt58++oypdz(tx*i+z)*pz8%^mtco2q9'
DEBUG = 'True'
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

[database]
ENGINE = 'django.db.backends.sqlite3'
NAME = 'scheduleone.db'