# Generated by Django 5.2 on 2025-05-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_effects', models.TextField()),
                ('drug_value', models.IntegerField()),
                ('drug_addiction_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drug_added_date', models.DateTimeField(auto_now_add=True)),
                ('drug_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('ingredient_effects', models.TextField()),
                ('ingredient_cost', models.IntegerField()),
                ('ingredient_added_date', models.DateTimeField(auto_now_add=True)),
                ('ingredient_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelOneDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_effects', models.TextField()),
                ('drug_value', models.IntegerField()),
                ('drug_addiction_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drug_added_date', models.DateTimeField(auto_now_add=True)),
                ('drug_updated_date', models.DateTimeField(auto_now=True)),
                ('drug_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.basedrugs')),
                ('drug_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.ingredients')),
            ],
        ),
    ]
